---
config_sections_to_sort:
  - config firewall address
  - config firewall addrgroup
  - config firewall internet-service-name
  - config router community-list
  - config router route-map
  - config system interface
  - config system zone

config_subsections_to_sort:
  config router bgp:
    - config neighbor
    - config network

config_sections_to_delete:
  - config vpn certificate local
